name: habit_note
description: "A simple note taking app with OCR functionality built with Clean Archtecture."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  easy_localization: ^3.0.7+1
  easy_localization_loader: ^2.0.2
  equatable: ^2.0.7
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  easy_localization_generator: ^0.3.3
  build_runner: ^2.4.14
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/onboaring.json
    - assets/lang/